version: '3.6'
networks:
  demo_net:
services:
  memo_server:
    container_name: object_detection_102
    build:
      context: .
    ports:
      - "10000:10000"
    volumes:
    #Mount . from host to docker. This allows to have changes show uu immediatelly
      - .:/new_work_dir
    command: uvicorn projectapp:app --host 0.0.0.0 --port 10000 --reload
